### ISSUE TITLE
backend to view posts/Comment on posts

### ISSUE THREAD

**Issue by HashirAKhan** [LuMiHNate/hz#10]

**Comment by fate89rosario** [comment]
Screen Recording 2021-05-01 at 12.33.39 AM.gif
<https://drive.google.com/file/d/1SKSl53PmgetEte6kq_jIv1ygXxcQCuwH/view?usp=drive_web>
 Screen Recording 2021-05-01 at 12.33.39 AM.gif.zip
<https://drive.google.com/file/d/12ll3dJ3CCAGMauNpyT0QRRPItlilmA1e/view?usp=drive_web>
